version: 2.1 # CicleCIのバージョンは2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs: # 指定したjobはbuildの1つ
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node # Dockerコンテナはrubyを使う?
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
